#!/usr/bin/python

import os, sys
os.mkdir(sys.argv[1])
with open(sys.argv[1]+'/CMakeLists.txt','w') as f:
  f.write('''
cmake_minimum_required(VERSION 2.8.3)
project(%s)
find_package(catkin REQUIRED COMPONENTS spiri_api)
include_directories(${catkin_INCLUDE_DIRS})
#add_executable(my_app my_src.cpp)
#target_link_libraries(my_app ${catkin_LIBRARIES})
'''%sys.argv[1])
